### ISSUE TITLE
Shell 40

### ISSUE THREAD

**Issue by monreal** [sync1211/wg-indicator#1]
Just found you extension which seems to be a nice workaround until gnome-shell gets native support for WireGuard. I had to change the metadata.json to make it work on shell 40. Mind adding that version in addition?

**Comment by sync1211** [comment]
I just installed it in Gnome 40.beta.0 (Xorg and Wayland) and it worked without any modifications.

What changes did you have to make to `metadata.json` to make it work on your system?

**Comment by monreal** [comment]
I just added version 40. Before that it would show AS incompatible in the extensions app.

**Comment by sync1211** [comment]
I've added Gnome 40.0 to the list of supported versions in `metadata.json` and submitted an update to extensions.gnome.org.

Thank you for letting me know about this issue.
