### ISSUE TITLE
BW icon

### ISSUE THREAD

**Issue by mario-tux** [sync1211/wg-indicator#3]
Could you consider to switch (or to provide an option) on a black-white icon to better fit in the design of standard icons in Gnome Shell?
I'm actually using a personal version of the icon but I can't provide a PR except to just overwrite the actual one.

![image](https://user-images.githubusercontent.com/4376789/118258045-ac6c7e80-b4af-11eb-8570-25cf1a71519f.png)

**Comment by sync1211** [comment]
Thank you for your suggestion.
I've been planning on adding a settings dialog for a while, so I will add this feature as an option within the settings dialog.

I've already created black and white versions of the indicator icon, so you don't need to submit your version.

**Comment by sync1211** [comment]
I've added the settings dialog with a selection of icon themes to choose from:

|                           Colored                            |                            White                             |                            Black                             |
| :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![colored](https://raw.githubusercontent.com/sync1211/wg-indicator/main/.github/screenshot_color.png) | ![white](https://raw.githubusercontent.com/sync1211/wg-indicator/main/.github/screenshot_white.png) | ![black](https://raw.githubusercontent.com/sync1211/wg-indicator/main/.github/screenshot_black.png) |
