### ISSUE TITLE
Doesn't seem to work on Gnome 40.4

### ISSUE THREAD

**Issue by roydisco** [sync1211/wg-indicator#6]
Was working previously.

**Comment by sync1211** [comment]
Thanks for the report. I've tested it on Gnome-Shell 40.4 and it worked without any issues?

Are there any errors reported in looking glass? (Press `CTRL` + `F2`, then enter "lg")

**Comment by roydisco** [comment]
No errors that way but on further inspection, something had deactivated all Gnome extensions.  Fixed by installing the Gnome Extensions flatpak and manually enabling.
