### ISSUE TITLE
Gnome 41 support

### ISSUE THREAD

**Issue by svnikolaev** [sync1211/wg-indicator#7]
Hello, can't install on Fedora 35 with Gnome 41

**Comment by sync1211** [comment]
Hi there,
what error are you getting when you try to install this extension on Gnome 41?

**Comment by Carbenium** [comment]
The extension is marked as 'outdated' on Gnome 41.
The [`shell-version`](https://github.com/sync1211/wg-indicator/blob/a1dbba8c309fa5963094ba864960965a84fa8746/metadata.json#L4) has to be updated (while making sure nothing broke with 41).

**Comment by sync1211** [comment]
Thanks for the clarification!

I've tested the extension on Gnome 41.0 without any issues. 

I have added Gnome 41 to the list of supported versions. The new version should now be available on [Gnome Extensions](extensions.gnome.org).
