### ISSUE TITLE
Support GNOME 42

### ISSUE THREAD

**Issue by monreal** [sync1211/wg-indicator#8]
I was hoping for native support of WireGuard in GNOME 42 / Fedora 36 but it seems this extension will be needed for another release cycle. Code changes seem to be needed as the extension GUI shows the following error when just adding version 42 to the manifest: 

Object 0xc4083b28928 is not a subclass of GObject_Object, it's a Object

**Comment by sync1211** [comment]
Sorry for the delay. I have just released a new version with support for GNOME 42 on extensions.gnome.org.
